repos:
- repo: local
  hooks:
    - id: black
      name: "Black"
      entry: black
      language: system
      pass_filenames: true
      types: ["python"]
    - id: isort
      name: "Isort"
      entry: isort
      language: system
      pass_filenames: true
      types: ["python"]

    - id: flake8
      name: "Flake8"
      entry: flake8
      language: system
      pass_filenames: true
      types: ["python"]

    - id: missing-migrations
      name: 'Missing migrations'
      entry: python manage.py makemigrations --check
      language: system
      pass_filenames: false
      types: ["file", "python"]

    - id: python-test
      name: 'Run Django tests'
      entry: coverage run manage.py test --noinput --keepdb
      language: system
      pass_filenames: false
      types: ["file", "python"]

    - id: coverage
      name: 'Confirm test coverage'
      entry: coverage report -m --fail-under 98
      language: system
      pass_filenames: false
      types: ["file", "python"]
