[tool.black]
# line-length default is 88.
# NOTE that at present, there are lines Black will not reformat to fit in 88 chars,
# and so we're telling flake8 to allow longer lines. But 88 is a good length for
# when Black can achieve it.
line-length = 88
target_version = ['py38']
exclude = '''

(
  /node_modules/
  | /venv/
)
'''

[tool.isort]
skip_glob = "docs,migrations,node_modules,venv,.direnv"
# https://black.readthedocs.io/en/stable/compatible_configs.html#isort :
profile = "black"
